apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/ipazosat/tekton-tutorial
    - name: revision
      value: main
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-tutorial-httpd-image
spec:
  type: image
  params:
    - name: url
      value: "registry.ocp.bmlab.int:5000/tektontutorial/httpd"
