apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/ipazosat/tekton-tutorial
    - name: revision
      value: main
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: httpd-image
spec:
  type: image
  params:
    - name: url
      value: "quay.io/ipazosat/tektontutorial/httpd:2.0"
