apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dockerfile-to-image
spec:
  params:
    - name: contextDir
      description: the context directory from where to build the application
    - name: tag
      description: the tag for the image you want to build
      type: string
  resources:
    - name: appSource
      type: git
    - name: appImage
      type: image
  tasks:
    - name: build-docker-file
      taskRef:
        name: build-app
      params:
        - name: contextDir
          value: $(params.contextDir)
        - name: tag
          value: $(params.tag)
      resources:
        inputs:
          - name: source
            resource: appSource
        outputs:
          - name: builtImage
            resource: appImage
